[package]
name = "rust_lesson06"
version = "0.1.0"
authors = ["Mr.Hat <shenghong6560@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
